#!/usr/bin/env python3
"""
FastAPI backend for PCA Sprint 5 Validation Layer
Handles deduplication checks and Obsidian note generation
"""

from fastapi import FastAPI, HTTPException, BackgroundTasks
from pydantic import BaseModel
from datetime import datetime
import os
import json
import logging
from pathlib import Path

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

app = FastAPI(
    title="PCA Validation Backend",
    description="Helper APIs for n8n validation workflow",
    version="1.0.0"
)

# Configuration from environment
NEO4J_HOST = os.getenv("NEO4J_HOST", "neo4j")
NEO4J_PORT = int(os.getenv("NEO4J_PORT", "7687"))
NEO4J_USER = os.getenv("NEO4J_USER", "neo4j")
NEO4J_PASSWORD = os.getenv("NEO4J_PASSWORD", "password")
OBSIDIAN_VAULT_PATH = os.getenv("OBSIDIAN_VAULT_PATH", "/vault")


# Models
class DeduplicationCheck(BaseModel):
    video_id: str


class ValidationResult(BaseModel):
    video_id: str
    title: str
    routing: str  # PROMOTE, INBOX, or ARCHIVE
    confidence: float
    credibility: int
    quality: int
    relevance: int
    alignment: int


class ObsidianNote(BaseModel):
    video_id: str
    title: str
    routing: str
    scores: dict
    assessment_date: str


# Endpoints

@app.get("/health")
async def health_check():
    """Health check endpoint"""
    return {
        "status": "healthy",
        "timestamp": datetime.utcnow().isoformat(),
        "neo4j": f"{NEO4J_HOST}:{NEO4J_PORT}",
        "obsidian_vault": OBSIDIAN_VAULT_PATH
    }


@app.post("/dedup-check")
async def check_deduplication(check: DeduplicationCheck) -> dict:
    """
    Check if video has already been validated.
    Returns: {exists: bool, validated_at: str?}
    """
    try:
        # In real implementation, query Neo4j here
        # For now, return not found (triggers validation)
        return {
            "exists": False,
            "video_id": check.video_id,
            "validated_at": None,
            "message": "Video not found in database - ready for validation"
        }
    except Exception as e:
        logger.error(f"Dedup check failed: {e}")
        return {
            "exists": False,
            "error": str(e)
        }


@app.post("/generate-note")
async def generate_obsidian_note(result: ValidationResult) -> dict:
    """
    Generate Obsidian markdown note from validation result.
    Writes to: {OBSIDIAN_VAULT}/assessments/{date}/{video_id}.md
    """
    try:
        # Create directory structure
        date_str = datetime.utcnow().strftime("%Y-%m-%d")
        assessments_dir = Path(OBSIDIAN_VAULT_PATH) / "assessments" / date_str
        assessments_dir.mkdir(parents=True, exist_ok=True)

        # Generate markdown content
        note_content = f"""---
video_id: {result.video_id}
title: {result.title}
routing: {result.routing}
confidence: {result.confidence}
assessed_at: {datetime.utcnow().isoformat()}
---

# {result.title}

## Assessment Results

| Dimension | Score |
|-----------|-------|
| Credibility | {result.credibility}/100 |
| Quality | {result.quality}/100 |
| Relevance | {result.relevance}/100 |
| Alignment | {result.alignment}/100 |

**Overall Confidence:** {result.confidence:.1%}

**Recommendation:** `{result.routing}`

## Assessment Metadata

- **Video ID:** `{result.video_id}`
- **Assessed:** {datetime.utcnow().isoformat()}
- **Source:** Dual-agent validation (Screening Agent + Critical Agent)

## Routing Logic

- **PROMOTE (>80):** High-quality, highly relevant content. Integrate immediately.
- **INBOX (60-80):** Moderate quality. Review for integration.
- **ARCHIVE (<60):** Low relevance or quality. Archive for reference.

---

*Generated by PCA Validation Layer*
"""

        # Write to file
        note_path = assessments_dir / f"{result.video_id}.md"
        with open(note_path, "w") as f:
            f.write(note_content)

        logger.info(f"Note generated: {note_path}")

        return {
            "success": True,
            "note_path": str(note_path),
            "video_id": result.video_id,
            "message": f"Note written to {note_path}"
        }

    except Exception as e:
        logger.error(f"Note generation failed: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@app.post("/log-validation")
async def log_validation(result: ValidationResult, background_tasks: BackgroundTasks) -> dict:
    """
    Log validation result for audit trail.
    In real implementation, stores in PostgreSQL.
    """
    log_entry = {
        "timestamp": datetime.utcnow().isoformat(),
        "video_id": result.video_id,
        "title": result.title,
        "routing": result.routing,
        "confidence": result.confidence,
        "scores": {
            "credibility": result.credibility,
            "quality": result.quality,
            "relevance": result.relevance,
            "alignment": result.alignment
        }
    }

    logger.info(f"Validation logged: {log_entry}")

    return {
        "success": True,
        "message": "Validation result logged"
    }


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(
        app,
        host="0.0.0.0",
        port=8000,
        log_level="info"
    )
